version: '3.3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4510-4530:4510-4530"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - DNS_RESOLVE_IP=10.0.2.20
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fiap
      - AWS_SECRET_ACCESS_KEY=fiap
      - DEFAULT_REGION=us-east-1
      - SERVICES=sqs
    volumes:
      - "./config/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      localstack:
        ipv4_address: 10.0.2.20

  application:
    build: .
    depends_on:
      localstack:
        condition: service_healthy
    environment:
    ports:
      - '8080:8080'
    expose:
      - '8080'
    dns:
      - 10.0.2.20
    networks:
      localstack:

networks:
  localstack:
    name: localstack
    ipam:
      config:
        - subnet: 10.0.2.0/24